FROM moveit/moveit2:jazzy-release AS base

SHELL ["/bin/bash", "-c"]
ENV DEBIAN_FRONTEND=noninteractive

# ----------------------------------------------------------------------
# System dependencies
# ----------------------------------------------------------------------
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    python3-colcon-common-extensions \
    python3-vcstool \
    python3-rosdep \
    libeigen3-dev \
    ros-jazzy-pinocchio \
    ros-jazzy-ros2-control \
    ros-jazzy-ros2-controllers \
    ros-jazzy-ros-gz \
    ros-jazzy-ros-gz-bridge \
    ros-jazzy-ros-gz-image \
    ros-jazzy-ros-gz-sim \
    ros-jazzy-gz-ros2-control \
    ros-jazzy-pick-ik \
    && rm -rf /var/lib/apt/lists/*

RUN git clone --recursive https://github.com/rbdl/rbdl.git /tmp/rbdl && \
    mkdir /tmp/rbdl/build && \
    cd /tmp/rbdl/build && \
    cmake .. -DRBDL_BUILD_ADDON_URDFREADER=ON && \
    make -j$(nproc) && \
    make install && \
    rm -rf /tmp/rbdl
RUN echo "/usr/local/lib" > /etc/ld.so.conf.d/rbdl.conf && \
    ldconfig

# ----------------------------------------------------------------------
# Workspace build stage
# ----------------------------------------------------------------------
FROM base AS builder

WORKDIR /ws

# Copy source INTO image (important for deployment mode)
COPY ./src /ws/src

RUN source /opt/ros/jazzy/setup.bash && \
    rosdep update && \
    rosdep install --from-paths src --ignore-src -r -y && \
    colcon build --executor sequential 

# ----------------------------------------------------------------------
# Runtime stage (small + clean)
# ----------------------------------------------------------------------
FROM base AS runtime

WORKDIR /ws

COPY --from=builder /ws/install /ws/install

RUN echo "source /opt/ros/jazzy/setup.bash" >> ~/.bashrc && \
    echo "source /ws/install/setup.bash" >> ~/.bashrc

ENTRYPOINT ["/bin/bash", "-c", "source /opt/ros/jazzy/setup.bash && source /ws/install/setup.bash && exec bash"]