FROM moveit/moveit2:jazzy-release

SHELL ["/bin/bash", "-c"]

ENV DEBIAN_FRONTEND=noninteractive

# ------------------------------------------------------------------------------
# Extra dependencies
# ------------------------------------------------------------------------------

RUN apt-get update && apt-get install -y \
    libeigen3-dev \
    ros-jazzy-pinocchio \
    python3-colcon-common-extensions \
    python3-vcstool \
    python3-rosdep \
    git \
    vim \
    && rm -rf /var/lib/apt/lists/*

# ------------------------------------------------------------------------------
# Workspace
# ------------------------------------------------------------------------------

WORKDIR /ws

COPY ./src /ws/src

RUN source /opt/ros/jazzy/setup.bash && \
    rosdep update && \
    rosdep install --from-paths src --ignore-src -r -y

RUN source /opt/ros/jazzy/setup.bash && \
    colcon build --symlink-install

RUN source install/setup.bash
CMD ["/bin/bash"]