Fullsim_Node:
  ros__parameters:
    joint_weights:
      columna_rot_joint: 0.01
      columna_flex_joint: 0.01
      elbow_roll_joint: 1.0
      elbow_yaw_joint: 1.0
      glenohumeral_pitch_joint: 1.0
      glenohumeral_roll_joint: 1.0
      glenohumeral_yaw_joint: 0.8
      sternoclavicular_pitch_joint: 0.1
      sternoclavicular_roll_joint: 0.1
      sternoclavicular_yaw_joint: 0.1
